### ISSUE TITLE
Not everyone is using gnome-terminal ;)

### ISSUE THREAD

**Issue by NicolasCARPi** [Anteste/WebMap#4]
One should be able to start things in their favorite term, or in a tmux pane.

**Comment by Anteste** [comment]
I agree with you am also not using gnome-terminal, but it's the only way to open and execute a command on a terminal.
I'm using Tmux I would like to run it on a Tmux pane but unfortunalty it's not available, am trying to find a fix.

We can execute in 2 ways
- in a gnome-terminal 
- as a background process

If you have any idea just let me now

**Comment by NicolasCARPi** [comment]
I would need to give it a longer look, but I think you can look into the `$TERM` and if it's `rxvt` use `rxvt -e`, for `xterm` it would be the same, etc...

**Comment by Anteste** [comment]
Thank you I will look into `$TERM`

**Comment by Anteste** [comment]
Hi Nicolas,
You can check the v1.0.4 update, I fixed the gnome-terminal issue ;)
